import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const porscheNext = localFont({
  src: "../fonts/PorscheNextWLa-Regular.woff",
  variable: "--font-porsche-next",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${porscheNext.variable} subpixel-antialiased`}>
        {children}
      </body>
    </html>
  );
}
